spring.datasource.url = jdbc:mysql://localhost:3306/SUT-RJ-1504
spring.datasource.username = root
spring.datasource.password = 123456
spring.datasource.driverClassName = com.mysql.jdbc.Driver
server.port=8080